


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.cinema.view;

import com.mycompany.cinema.Client;
import com.mycompany.cinema.service.ClientService;
import java.awt.Frame;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author albertoesperon
 */
public class FenetreEspaceClient extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreEspaceClient.class.getName());

    /**
     * Creates new form EspaceClient
     */
    /**
     * CONSTRUCTEUR MODIFIÉ Remplacez le constructeur généré par NetBeans par
     * celui-ci.
     */
    public FenetreEspaceClient(java.awt.Frame parent, boolean modal, ClientService clientService, Client clientConnecte) {

        // Appel au code généré par NetBeans pour construire l'interface visuelle
        initComponents();

        // --- C'est ici qu'on ajoute notre logique après la construction ---
        // 1. On crée les instances de nos panneaux personnalisés
        //    (Ce sont des classes que vous avez déjà dans votre projet)
        JPanel infosPanel = new PanneauInfosPersonnelles(clientService, clientConnecte, this);
        PanneauHistoriqueReservations historiquePanel = new PanneauHistoriqueReservations(clientService, clientConnecte);

        // 2. On remplace les panneaux vides (jPanel1, jPanel2) créés par le designer
        //    par nos vrais panneaux. L'index 0 correspond au premier onglet, 1 au second.
        tabbedPane.setComponentAt(0, infosPanel);
        tabbedPane.setComponentAt(1, historiquePanel);

        // 3. On ajoute l'écouteur d'événement qui se déclenche quand on change d'onglet.
        tabbedPane.addChangeListener(new ChangeListener() {
            @Override // Annotation recommandée par la doctrine (p. 162)
            public void stateChanged(ChangeEvent e) {
                // Si l'onglet qui est maintenant visible est celui de l'historique...
                if (tabbedPane.getSelectedComponent() == historiquePanel) {
                    // ...alors on appelle sa méthode publique pour recharger les données.
                    historiquePanel.chargerHistorique();
                }
            }
        });

        // 4. On finalise la configuration de la fenêtre (titre, taille, position).
        this.setTitle("Mon Espace Client");
        this.setSize(800, 600);
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Mes informations", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Historique des réservations", jPanel2);

        getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
