/*
 * Ce fichier a été généré par NetBeans.
 * Il a ensuite été modifié pour intégrer la logique métier.
 */
package com.mycompany.cinema.view;

// Imports nécessaires
import com.mycompany.cinema.Film;
import com.mycompany.cinema.service.CinemaService;
import java.awt.Component;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 * Panneau affichant la liste des films à l'affiche.
 * @author albertoesperon
 */
// CORRECTION : Le nom de la classe correspond maintenant au nom du fichier.
public class FilmList extends javax.swing.JPanel {

    // --- VOS VARIABLES D'INSTANCE ---
    private final CinemaService cinemaService;
    private DefaultListModel<Film> filmListModel;
    private FilmSelectionListener selectionListener;

    // --- VOTRE INTERFACE DE COMMUNICATION ---
    public interface FilmSelectionListener {
        void onFilmSelected(Film film);
    }

    /**
     * CONSTRUCTEUR MODIFIÉ
     */
    public FilmList(CinemaService cinemaService) {
        this.cinemaService = cinemaService;
        initComponents();
        this.setupList();
        this.loadFilms();
    }
    
    /**
     * Méthode pour configurer le modèle de la liste et son rendu.
     */
    private void setupList() {
        filmListModel = new DefaultListModel<>();
        filmJList.setModel(filmListModel);

        // Rendu personnalisé pour n'afficher que le titre
        filmJList.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Film) {
                    setText(((Film) value).getTitre());
                }
                return this;
            }
        });

        // Écouteur de sélection
        filmJList.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting() && selectionListener != null) {
                    Film selectedFilm = filmJList.getSelectedValue();
                    if (selectedFilm != null) {
                        selectionListener.onFilmSelected(selectedFilm);
                    }
                }
            }
        });
    }

    /**
     * Charge la liste des films depuis le service.
     */
    private void loadFilms() {
        filmListModel.clear();
        List<Film> films = cinemaService.getFilmsAffiche();
        for (Film film : films) {
            filmListModel.addElement(film);
        }
    }

    /**
     * Méthode publique pour que le parent puisse s'abonner.
     */
    public void setFilmSelectionListener(FilmSelectionListener listener) {
        this.selectionListener = listener;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        filmJList = new javax.swing.JList<>();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Films à l'affiche"));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(filmJList);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<com.mycompany.cinema.Film> filmJList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
