// Dans le fichier PaiementPanel.java
package com.mycompany.cinema.view;

import java.time.LocalDate;
import javax.swing.JOptionPane;

public class PaiementPanel extends javax.swing.JPanel {

    // --- INTERFACE DE COMMUNICATION ---
    public interface PaiementListener {

        void onPaiementValide(); // Informer que le paiement est "réussi"

        void onRetour();        // Informer qu'il faut revenir en arrière
    }
    private PaiementListener listener;

    public PaiementPanel() {
        initComponents();
    }

    // Méthode pour que la fenêtre principale puisse s'abonner aux événements
    public void setListener(PaiementListener listener) {
        this.listener = listener;
    }

    // Méthode pour afficher le montant à payer
    public void setMontantTotal(double montant) {
        totalAmountLabel.setText(String.format("%.2f €", montant));
    }

    // La logique de validation sera ici
    private void validerPaiement() {
        String cardNumber = cardNumberField.getText().trim();
        String expiryDate = expiryDateField.getText().trim();
        String cvv = cvvField.getText().trim();

        // --- 1. VALIDATION DU FORMAT DES CHAMPS (AVEC REGEX) ---
        // Regex pour 16 chiffres
        String cardRegex = "^\\d{16}$";
        // Regex pour MM/AA, avec MM de 01 à 12
        String expiryRegex = "^(0[1-9]|1[0-2])\\/\\d{2}$";
        // Regex pour 3 ou 4 chiffres
        String cvvRegex = "^\\d{3,4}$";

        if (!cardNumber.matches(cardRegex)) {
            JOptionPane.showMessageDialog(this, "Le numéro de carte doit contenir exactement 16 chiffres.", "Erreur de format", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!expiryDate.matches(expiryRegex)) {
            JOptionPane.showMessageDialog(this, "La date d'expiration doit être au format MM/AA (ex: 04/28).", "Erreur de format", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!cvv.matches(cvvRegex)) {
            JOptionPane.showMessageDialog(this, "Le CVV doit contenir 3 ou 4 chiffres.", "Erreur de format", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // --- 2. VALIDATION LOGIQUE DE LA DATE D'EXPIRATION ---
        try {
            // Découper la chaîne "MM/AA" pour obtenir le mois et l'année
            String[] dateParts = expiryDate.split("/");
            int moisCarte = Integer.parseInt(dateParts[0]);
            // Convertir l'année courte en année complète (ex: "28" -> 2028)
            int anneeCarte = 2000 + Integer.parseInt(dateParts[1]);

            // Obtenir le mois et l'année actuels
            LocalDate dateActuelle = LocalDate.now();
            int moisActuel = dateActuelle.getMonthValue();
            int anneeActuelle = dateActuelle.getYear();

            // Logique de comparaison orthodoxe
            boolean estExpiree = false;
            if (anneeCarte < anneeActuelle) {
                // L'année de la carte est passée -> expirée
                estExpiree = true;
            } else if (anneeCarte == anneeActuelle) {
                // L'année est la même, on compare les mois
                if (moisCarte < moisActuel) {
                    // Le mois de la carte est passé -> expirée
                    estExpiree = true;
                }
            }
            // Si l'année de la carte est dans le futur, 'estExpiree' reste 'false'.
            // Si l'année est la même et le mois est le même ou futur, 'estExpiree' reste 'false'.

            if (estExpiree) {
                JOptionPane.showMessageDialog(this, "Cette carte bancaire est expirée. Veuillez entrer une carte valide", "Carte invalide", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception e) {
            // Sécurité en cas de problème lors de la conversion, bien que peu probable grâce à la regex
            JOptionPane.showMessageDialog(this, "La date d'expiration n'a pas pu être validée.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // --- 3. SI TOUTES LES VALIDATIONS PASSENT ---
        // On prévient la fenêtre principale que le paiement est "accepté"
        if (listener != null) {
            listener.onPaiementValide();
        }
    }

    public void reset() {
        cardNumberField.setText("");
        expiryDateField.setText("");
        cvvField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cardNumberField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        expiryDateField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cvvField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        retourButton = new javax.swing.JButton();
        payerButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Paiement et confirmation");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        formPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations de paiement"));
        formPanel.setPreferredSize(new java.awt.Dimension(400, 200));
        formPanel.setLayout(new java.awt.GridLayout(0, 2, 0, 10));

        jLabel6.setText("Numéro de carte : ");
        formPanel.add(jLabel6);
        formPanel.add(cardNumberField);

        jLabel7.setText("Date d'expiration (MM/AA) :");
        formPanel.add(jLabel7);
        formPanel.add(expiryDateField);

        jLabel8.setText("CVV : ");
        formPanel.add(jLabel8);
        formPanel.add(cvvField);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Montant total : ");
        formPanel.add(jLabel2);

        totalAmountLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        totalAmountLabel.setText("00,00 €");
        formPanel.add(totalAmountLabel);

        add(formPanel, java.awt.BorderLayout.CENTER);

        retourButton.setText("<< Retour aux snacks");
        retourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourButtonActionPerformed(evt);
            }
        });
        jPanel1.add(retourButton);

        payerButton.setText("Valider le paiement");
        payerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(payerButton);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void retourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourButtonActionPerformed
        if (listener != null) {
            listener.onRetour();
        }// TODO add your handling code here:
    }//GEN-LAST:event_retourButtonActionPerformed

    private void payerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payerButtonActionPerformed
        validerPaiement();// TODO add your handling code here:
    }//GEN-LAST:event_payerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cardNumberField;
    private javax.swing.JTextField cvvField;
    private javax.swing.JTextField expiryDateField;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton payerButton;
    private javax.swing.JButton retourButton;
    private javax.swing.JLabel totalAmountLabel;
    // End of variables declaration//GEN-END:variables
}
