/*
 * PanneauInfosPersonnelles.java
 * Formulaire permettant au client de modifier ses informations personnelles
 * ou de supprimer son compte.
 */
package com.mycompany.cinema.view;

import com.mycompany.cinema.Client;
import com.mycompany.cinema.service.ClientService;
import java.awt.Color;
import java.util.Arrays;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class PanneauInfosPersonnelles extends javax.swing.JPanel {

    private final ClientService clientService;
    private final Client clientConnecte;
    private final JDialog parentDialog; // Référence à la fenêtre qui le contient (EspaceClient)
    private final FenetrePrincipaleClient fenetrePrincipale;

    public PanneauInfosPersonnelles(ClientService clientService, Client clientConnecte, JDialog parentDialog, FenetrePrincipaleClient fenetrePrincipale) {
        this.clientService = clientService;
        this.clientConnecte = clientConnecte;
        this.parentDialog = parentDialog;
        this.fenetrePrincipale = fenetrePrincipale;
        initComponents();
        chargerInfosClient();
    }

    /**
     * Pré-remplit le champ du nom avec l'information actuelle du client.
     */
    private void chargerInfosClient() {
        nomField.setText(clientConnecte.getNom());
    }

    /**
     * Logique exécutée après clic sur le bouton "Mettre à jour".
     */
    private void actionMettreAJour() {
        String nom = nomField.getText().trim();
        if (nom.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Le nom ne peut pas être vide.", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
            return;
        }

        char[] nouveauMdp = passField.getPassword();
        char[] confirmationMdp = confirmPassField.getPassword();

        // On ne met à jour le mot de passe que si l'utilisateur a tapé quelque chose.
        boolean motDePasseChange = nouveauMdp.length > 0;

        if (motDePasseChange) {
            if (!Arrays.equals(nouveauMdp, confirmationMdp)) {
                JOptionPane.showMessageDialog(this, "Les mots de passe ne correspondent pas.", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
                passField.setText("");
                confirmPassField.setText("");
                return;
            }
            // Si les mots de passe correspondent, on met à jour l'objet client
            clientConnecte.setMotDePasse(new String(nouveauMdp));
        }

        clientConnecte.setNom(nom);

        try {
            clientService.modifierCompteClient(clientConnecte);
            JOptionPane.showMessageDialog(this, "Vos informations ont été mises à jour avec succès.", "Succès", JOptionPane.INFORMATION_MESSAGE);
            // On vide les champs de mot de passe après une mise à jour réussie
            passField.setText("");
            confirmPassField.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erreur lors de la mise à jour : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Logique exécutée lors du clic sur le bouton "Supprimer mon compte".
     */
    private void actionSupprimerCompte() {
        int reponse = JOptionPane.showConfirmDialog(
                this,
                "Êtes-vous absolument sûr de vouloir supprimer votre compte ?\nCette action est irréversible et toutes vos réservations seront annulées.",
                "Confirmation de Suppression",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (reponse == JOptionPane.YES_OPTION) {
            try {
                clientService.supprimerCompteClient(clientConnecte.getId());

                JOptionPane.showMessageDialog(this,
                        "Votre compte a été supprimé avec succès. Un email de confirmation vous sera envoyé.",
                        "Compte supprimé",
                        JOptionPane.INFORMATION_MESSAGE
                );

                this.fenetrePrincipale.dispose(); // Ferme la fenêtre principale
                this.parentDialog.dispose(); // Ferme la fenêtre de l'espace 

                // Retour à l'écran de connexion
                new FenetreConnexion().setVisible(true);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erreur lors de la suppression du compte : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        confirmPassField = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        majButton = new javax.swing.JButton();
        supprimerButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nom :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 94;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 12, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Nouveau mot de passe :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 12, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Confirmer le mot de passe :");
        jLabel3.setPreferredSize(new java.awt.Dimension(180, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 12, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        nomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 12);
        jPanel1.add(nomField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 12);
        jPanel1.add(passField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 235, 12);
        jPanel1.add(confirmPassField, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        majButton.setText("Mettre à jour");
        majButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majButtonActionPerformed(evt);
            }
        });
        jPanel2.add(majButton);

        supprimerButton.setBackground(new java.awt.Color(255, 102, 102));
        supprimerButton.setForeground(new java.awt.Color(255, 255, 255));
        supprimerButton.setText("Supprimer mon compte ");
        supprimerButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        supprimerButton.setOpaque(true);
        supprimerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerButtonActionPerformed(evt);
            }
        });
        jPanel2.add(supprimerButton);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void nomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomFieldActionPerformed
    }//GEN-LAST:event_nomFieldActionPerformed

    private void supprimerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerButtonActionPerformed
        actionSupprimerCompte();
    }//GEN-LAST:event_supprimerButtonActionPerformed

    private void majButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majButtonActionPerformed
        actionMettreAJour();
    }//GEN-LAST:event_majButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton majButton;
    private javax.swing.JTextField nomField;
    private javax.swing.JPasswordField passField;
    private javax.swing.JButton supprimerButton;
    // End of variables declaration//GEN-END:variables

}
