/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.cinema.view;

import java.util.Arrays;
import javax.swing.JOptionPane;

public class ReinitialiserMotDePasse extends javax.swing.JDialog {

    // Cette variable stockera le nouveau mot de passe si et seulement si la validation est réussie.
    private String nouveauMotDePasse = null;

    /**
     * Constructeur.
     */
    public ReinitialiserMotDePasse(java.awt.Frame parent, boolean modal) {
        super(parent, "Réinitialiser le mot de passe", modal);
        initComponents();
        setLocationRelativeTo(parent); // Centre la fenêtre sur son parent
        getRootPane().setDefaultButton(enregistrerButton); // Permet d'appuyer sur "Entrée"
    }

    /**
     * Méthode publique pour afficher le dialogue et retourner le résultat.
     * C'est la seule méthode que la fenêtre Login appellera.
     *
     * @return Le nouveau mot de passe validé, ou null si l'utilisateur a
     * annulé.
     */
    public String showDialog() {
        this.setVisible(true);
        return this.nouveauMotDePasse;
    }

    /**
     * Logique exécutée lorsque l'utilisateur clique sur "Enregistrer".
     */
    private void actionEnregistrer() {
        char[] p1 = nouveauPassField.getPassword();
        String motDePasseString = new String(p1);
        char[] p2 = confirmPassField.getPassword();

        try {
            // --- VALIDATION DE LA ROBUSTESSE AVEC DES REGEX SÉPARÉES ---

            // Règle 1 : Vérifier la longueur
            if (motDePasseString.length() < 8) {
                JOptionPane.showMessageDialog(this, "Le mot de passe doit contenir au moins 8 caractères.", "Mot de passe non conforme", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Règle 2 : Doit contenir au moins une minuscule
            if (!motDePasseString.matches(".*[a-z].*")) {
                JOptionPane.showMessageDialog(this, "Le mot de passe doit contenir au moins une lettre minuscule.", "Mot de passe non conforme", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Règle 3 : Doit contenir au moins une majuscule
            if (!motDePasseString.matches(".*[A-Z].*")) {
                JOptionPane.showMessageDialog(this, "Le mot de passe doit contenir au moins une lettre majuscule.", "Mot de passe non conforme", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Règle 4 : Doit contenir au moins un chiffre
            if (!motDePasseString.matches(".*[0-9].*")) {
                JOptionPane.showMessageDialog(this, "Le mot de passe doit contenir au moins un chiffre.", "Mot de passe non conforme", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // --- FIN DE LA VALIDATION DE ROBUSTESSE ---
            // On vérifie que les deux mots de passe correspondent
            if (!Arrays.equals(p1, p2)) {
                JOptionPane.showMessageDialog(this, "Les mots de passe ne correspondent pas.", "Validation", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Si toutes les validations sont passées :
            this.nouveauMotDePasse = motDePasseString;
            this.dispose();

        } finally {
            // Pour la sécurité, on efface les tableaux de caractères après utilisation.
            Arrays.fill(p1, '\0');
            Arrays.fill(p2, '\0');
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        enregistrerButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nouveauPassField = new javax.swing.JPasswordField();
        confirmPassField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane1.setLayout(new java.awt.FlowLayout());

        enregistrerButton.setText("Enregistrer");
        enregistrerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(enregistrerButton);

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(annulerButton);

        getContentPane().add(jLayeredPane1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setText("Nouveau mot de passe : ");

        jLabel2.setText("Confirmer le mot de passe : ");

        jLayeredPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(nouveauPassField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(confirmPassField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nouveauPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nouveauPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(jLayeredPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enregistrerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerButtonActionPerformed
        actionEnregistrer();// TODO add your handling code here:
    }//GEN-LAST:event_enregistrerButtonActionPerformed

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_annulerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerButton;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JButton enregistrerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPasswordField nouveauPassField;
    // End of variables declaration//GEN-END:variables
}
