/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
// Dans le fichier SnackLignePanel.java
package com.mycompany.cinema.view;

import com.mycompany.cinema.LignePanier;
import com.mycompany.cinema.ProduitSnack;
import java.text.DecimalFormat;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

public class SnackLignePanel extends javax.swing.JPanel {

    private final LignePanier lignePanier; // Le modèle de données de ce panneau
    private static final DecimalFormat CURRENCY_FORMATTER = new DecimalFormat("#,##0.00 €");

    /**
     * Le constructeur prend en paramètre le modèle de données qu'il doit
     * afficher.
     */
    public SnackLignePanel(LignePanier lignePanier) {
        this.lignePanier = lignePanier;
        initComponents(); // Méthode de NetBeans

        // On configure les composants graphiques avec les données du modèle
        ProduitSnack produit = lignePanier.getProduit();

        String labelText = "<html><b>" + produit.getNomProduit() + "</b><br>"
                + "<i>" + produit.getDescription() + "</i><br>"
                + "<font color='blue'>Prix: " + CURRENCY_FORMATTER.format(produit.getPrixVente()) + "</font></html>";
        infoLabel.setText(labelText);

        SpinnerNumberModel spinnerModel = new SpinnerNumberModel(
                lignePanier.getQuantite(), // Valeur initiale
                0, // Minimum
                produit.getStock(), // Maximum
                1 // Pas
        );
        quantiteSpinner.setModel(spinnerModel);

        // On ajoute un écouteur pour mettre à jour le modèle quand la vue change
        quantiteSpinner.addChangeListener(e -> {
            int nouvelleQuantite = (Integer) quantiteSpinner.getValue();
            this.lignePanier.setQuantite(nouvelleQuantite);
        });
    }

    // Dans le fichier SnackLignePanel.java (VÉRIFICATION)
    public int getQuantite() {
        // Cette méthode doit retourner la valeur ACTUELLE du spinner.
        return (Integer) quantiteSpinner.getValue();
    }
    
    /**
     * Retourne l'objet ProduitSnack associé à cette ligne.
     * Nécessaire pour obtenir le nom, le prix, etc.
     */
    public ProduitSnack getProduit() {
        return this.lignePanier.getProduit();
    }

    // Méthodes pour que le panneau parent puisse interagir avec ce composant
    public JSpinner getSpinner() {
        return quantiteSpinner;
    }

    public void reset() {
        quantiteSpinner.setValue(0);
        this.lignePanier.setQuantite(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoLabel = new javax.swing.JLabel();
        quantiteSpinner = new javax.swing.JSpinner();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        setLayout(new java.awt.BorderLayout());

        infoLabel.setText("jLabel1");
        add(infoLabel, java.awt.BorderLayout.CENTER);
        add(quantiteSpinner, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoLabel;
    private javax.swing.JSpinner quantiteSpinner;
    // End of variables declaration//GEN-END:variables
}
