package com.mycompany.cinema.view.admin;

import com.mycompany.cinema.Personnel;
import com.mycompany.cinema.service.AdminService;
import java.awt.Component; // Importation nécessaire
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class AdminMain extends javax.swing.JFrame {

    private final AdminService adminService;
    private final Personnel personnelConnecte;

    public AdminMain(AdminService adminService, Personnel personnelConnecte) {
        this.adminService = adminService;
        this.personnelConnecte = personnelConnecte;

        initComponents(); // Construit les composants visuels (le JTabbedPane)
        
        // Configuration de la fenêtre (placée ici pour la clarté)
        setTitle("Panneau d'Administration - " + personnelConnecte.getPrenom() + " " + personnelConnecte.getNom());
        setLocationRelativeTo(null); // Centrer après que la taille soit connue

        // --- Logique d'assemblage des onglets ---
        setupTabs();
    }
    
    /**
     * Crée et ajoute tous les panneaux de gestion aux onglets.
     */
    private void setupTabs() {
        // CORRECTION DES NOMS DE CLASSE : Appel à vos nouvelles unités.
        tabbedPane.addTab("Gestion Films", new GestionFilms(this.adminService));
        tabbedPane.addTab("Gestion Séances", new GestionSeancesPanel(this.adminService)); // Reste à convertir
        tabbedPane.addTab("Gestion Salles", new GestionSalles(this.adminService));
        tabbedPane.addTab("Gestion Personnel", new GestionPersonnel(this.adminService));
        tabbedPane.addTab("Gestion Tarifs", new GestionTarifsPanel(this.adminService)); // Reste à convertir
        tabbedPane.addTab("Gestion Snacking", new GestionProduitsSnackPanel(this.adminService));
        tabbedPane.addTab("Rapports de Ventes", new ReportingPanel(this.adminService));
        
        // Ajout du listener pour le rafraîchissement automatique.
        tabbedPane.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                Component selectedComponent = tabbedPane.getSelectedComponent();
                
                // Exemple pour un futur panneau nécessitant un rafraîchissement.
                if (selectedComponent instanceof GestionSeancesPanel) {
                    // ((GestionSeancesPanel) selectedComponent).rafraichirDonnees();
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
