/*
 * FenetreAdmin.java
 * Fenêtre principale du panneau d'administration.
 * Elle utilise un JTabbedPane pour naviguer entre les différents modules de gestion.
 */
package com.mycompany.cinema.view.admin;

import com.mycompany.cinema.Personnel;
import com.mycompany.cinema.service.AdminService;
import com.mycompany.cinema.view.FenetreConnexion;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class FenetreAdmin extends javax.swing.JFrame {

    private final AdminService adminService;
    private final Personnel personnelConnecte;

    public FenetreAdmin(AdminService adminService, Personnel personnelConnecte) {
        this.adminService = adminService;
        this.personnelConnecte = personnelConnecte;

        initComponents();

        setTitle("Panneau d'Administration - " + personnelConnecte.getPrenom() + " " + personnelConnecte.getNom());
        setSize(1280, 720);
        setLocationRelativeTo(null);

        configurerOnglets();
    }

    /**
     * Crée les instances de tous les panneaux de gestion et les ajoute aux
     * onglets.
     */
    private void configurerOnglets() {
        tabbedPane.addTab("Gestion Films", new PanneauGestionFilms(this.adminService));
        tabbedPane.addTab("Gestion Séances", new PanneauGestionSeances(this.adminService));
        tabbedPane.addTab("Gestion Genres", new PanneauGestionGenres(this.adminService));
        tabbedPane.addTab("Gestion Salles", new PanneauGestionSalles(this.adminService));
        tabbedPane.addTab("Gestion Personnel", new PanneauGestionPersonnel(this.adminService));
        tabbedPane.addTab("Gestion Planning", new PanneauGestionPlanning(this.adminService));
        tabbedPane.addTab("Gestion Tarifs", new PanneauGestionTarifs(this.adminService));
        tabbedPane.addTab("Gestion Snacking", new PanneauGestionProduitSnack(this.adminService));
        tabbedPane.addTab("Rapports de Ventes", new PanneauRapportVentes(this.adminService));

        tabbedPane.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                Component selectedComponent = tabbedPane.getSelectedComponent();

                if (selectedComponent instanceof PanneauGestionFilms) {
                    ((PanneauGestionFilms) selectedComponent).rafraichirDonnees();
                } else if (selectedComponent instanceof PanneauGestionSeances) {
                    ((PanneauGestionSeances) selectedComponent).rafraichirDonnees();
                } else if (selectedComponent instanceof PanneauGestionSalles) {
                    ((PanneauGestionSalles) selectedComponent).rafraichirDonnees();
                } else if (selectedComponent instanceof PanneauGestionPersonnel) {
                    ((PanneauGestionPersonnel) selectedComponent).rafraichirDonnees();
                } else if (selectedComponent instanceof PanneauGestionTarifs) {
                    ((PanneauGestionTarifs) selectedComponent).rafraichirDonnees();
                } else if (selectedComponent instanceof PanneauGestionProduitSnack) {
                    ((PanneauGestionProduitSnack) selectedComponent).rafraichirDonnees();
                } else if (selectedComponent instanceof PanneauRapportVentes) {
                    ((PanneauRapportVentes) selectedComponent).chargerToutesLesTablesEtTotaux();
                } else if (selectedComponent instanceof PanneauGestionPlanning) {
                    ((PanneauGestionPlanning) selectedComponent).rafraichirDonnees();
                } else if (selectedComponent instanceof PanneauGestionGenres) {
                    ((PanneauGestionGenres) selectedComponent).rafraichirDonnees();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deconnexionButton = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        deconnexionButton.setText("Déconnexion");
        deconnexionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deconnexionButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deconnexionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionButtonActionPerformed
        // Étape 1 : On demande la confirmation à l'utilisateur.
        Object[] options = {"Oui", "Non"};
        int reponse = JOptionPane.showOptionDialog(
                this, "Êtes-vous sûr de vouloir vous déconnecter ?",
                "Confirmation de déconnexion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, 
                options, 
                options[0] // Le bouton par défaut ("Oui")
        );

        // Étape 2 : Si l'utilisateur confirme, on ferme la fenêtre actuelle
        if (reponse == JOptionPane.YES_OPTION) {
            this.dispose();

            // On lance une nouvelle fenêtre de connexion.
            new FenetreConnexion().setVisible(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_deconnexionButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deconnexionButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
