package com.mycompany.cinema.view.admin;

import com.mycompany.cinema.Personnel;
import com.mycompany.cinema.ProduitSnack;
import com.mycompany.cinema.service.AdminService;
import java.awt.Component;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PointDeVente extends javax.swing.JFrame {

    private final AdminService adminService;
    private final Personnel vendeurConnecte;
    private DefaultListModel<ProduitSnack> listModel;
    private DefaultTableModel tableModel;
    private Map<ProduitSnack, Integer> panier;

    public PointDeVente(AdminService adminService, Personnel vendeur) {
        this.adminService = adminService;
        this.vendeurConnecte = vendeur;

        initComponents();
        initModelsAndRenderers();

        this.panier = new HashMap<>();
        chargerProduits();

        setTitle("Point de Vente - " + vendeur.getPrenom() + " " + vendeur.getNom());
        setLocationRelativeTo(null);
    }

    private void initModelsAndRenderers() {
        listModel = new DefaultListModel<>();
        listeProduits.setModel(listModel);

        String[] columnNames = {"Produit", "Quantité", "Prix Unitaire", "Sous-total"};
        tableModel = new DefaultTableModel(columnNames, 0) {
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        panierTable.setModel(tableModel);

        listeProduits.setCellRenderer(new DefaultListCellRenderer() {
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof ProduitSnack) {
                    ProduitSnack p = (ProduitSnack) value;
                    setText(p.getNomProduit() + " (" + String.format("%.2f", p.getPrixVente()) + " €) - Stock: " + p.getStock());
                }
                return this;
            }
        });
    }

    private void chargerProduits() {
        try {
            listModel.clear();
            List<ProduitSnack> produits = adminService.getAllProduitsSnack();
            for (ProduitSnack p : produits) {
                listModel.addElement(p);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur au chargement des produits.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void actionAjouter() {
        ProduitSnack selected = listeProduits.getSelectedValue();
        if (selected == null) {
            return;
        }

        int quantiteActuelle = 0;
        if (panier.containsKey(selected)) {
            quantiteActuelle = panier.get(selected);
        }
        panier.put(selected, quantiteActuelle + 1);

        mettreAJourPanier();
    }

    private void actionAnnuler() {
        panier.clear();
        mettreAJourPanier();
    }

    private void actionValider() {
        if (panier.isEmpty()) {
            return;
        }
        try {
            adminService.enregistrerVenteSnack(vendeurConnecte.getId(), 1, panier);
            JOptionPane.showMessageDialog(this, "Vente enregistrée avec succès !", "Succès", JOptionPane.INFORMATION_MESSAGE);
            actionAnnuler();
            chargerProduits();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erreur: " + ex.getMessage(), "Erreur de Vente", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void mettreAJourPanier() {
        tableModel.setRowCount(0);
        double totalGeneral = 0.0;

        for (ProduitSnack p : panier.keySet()) {
            Integer qte = panier.get(p);
            double sousTotal = p.getPrixVente() * qte;
            tableModel.addRow(new Object[]{
                p.getNomProduit(),
                qte,
                String.format("%.2f €", p.getPrixVente()),
                String.format("%.2f €", sousTotal)
            });
            totalGeneral += sousTotal;
        }
        totalLabel.setText("TOTAL : " + String.format("%.2f €", totalGeneral));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panneauGauche = new javax.swing.JPanel();
        ajouterButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listeProduits = new javax.swing.JList<>();
        panneauDroite = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panierTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        annulerButton = new javax.swing.JButton();
        validerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panneauGauche.setBorder(javax.swing.BorderFactory.createTitledBorder("Produits disponibles"));
        panneauGauche.setPreferredSize(new java.awt.Dimension(300, 484));

        ajouterButton.setText("Ajouter au panier");
        ajouterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listeProduits);

        javax.swing.GroupLayout panneauGaucheLayout = new javax.swing.GroupLayout(panneauGauche);
        panneauGauche.setLayout(panneauGaucheLayout);
        panneauGaucheLayout.setHorizontalGroup(
            panneauGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauGaucheLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panneauGaucheLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(ajouterButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panneauGaucheLayout.setVerticalGroup(
            panneauGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauGaucheLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ajouterButton)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(panneauGauche);

        panneauDroite.setBorder(javax.swing.BorderFactory.createTitledBorder("Vente en cours"));
        panneauDroite.setLayout(new java.awt.BorderLayout());

        panierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(panierTable);

        panneauDroite.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        totalLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        totalLabel.setText("TOTAL : 00,00 €");
        jPanel2.add(totalLabel, java.awt.BorderLayout.LINE_START);

        annulerButton.setText("Annuler la vente ");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(annulerButton);

        validerButton.setText("Valider la vente");
        validerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(validerButton);

        jPanel2.add(buttonsPanel, java.awt.BorderLayout.LINE_END);

        panneauDroite.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setRightComponent(panneauDroite);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterButtonActionPerformed
        actionAjouter();// TODO add your handling code here:
    }//GEN-LAST:event_ajouterButtonActionPerformed

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        actionAnnuler();// TODO add your handling code here:
    }//GEN-LAST:event_annulerButtonActionPerformed

    private void validerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerButtonActionPerformed
        actionValider();// TODO add your handling code here:
    }//GEN-LAST:event_validerButtonActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterButton;
    private javax.swing.JButton annulerButton;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList<com.mycompany.cinema.ProduitSnack> listeProduits;
    private javax.swing.JTable panierTable;
    private javax.swing.JPanel panneauDroite;
    private javax.swing.JPanel panneauGauche;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton validerButton;
    // End of variables declaration//GEN-END:variables
}
